// previewTheme类型：'default' | 'github' | 'vuepress' | 'mk-cute' | 'smart-blue' | 'cyanosis'
export const toolbars: any = [
    'bold',
    'underline',
    'italic',
    'strikeThrough',
    '-',
    'title',
    'sub',
    'sup',
    'quote',
    'unorderedList',
    'orderedList',
    'task',
    '-',
    'codeRow',
    'code',
    'link',
    'image',
    'table',
    'mermaid',
    'katex',
    // 0,
    1,
    2,
    3,
    '-',
    'revoke',
    'next',
    'save',
  
    '=',
    'prettier',
    // 'pageFullscreen',
    'fullscreen',
    'preview',
    // 'htmlPreview',
    'catalog',
    // 'github',
  ];