// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Backtop: typeof import('./src/components/backtop/backtop.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Emoji: typeof import('./src/components/md-edits/emoji/emoji.vue')['default']
    Github: typeof import('./src/components/header/github/github.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    I18n: typeof import('./src/components/I18n/index.vue')['default']
    Lang: typeof import('./src/components/header/lang/lang.vue')['default']
    Logo: typeof import('./src/components/header/logo/logo.vue')['default']
    Manage: typeof import('./src/components/manage/manage.vue')['default']
    Menus: typeof import('./src/components/menus/menus.vue')['default']
    Nav: typeof import('./src/components/header/nav/nav.vue')['default']
    Read: typeof import('./src/components/md-edits/read/read.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./src/components/header/theme/theme.vue')['default']
    UploadImg: typeof import('./src/components/upload/upload-img.vue')['default']
    User: typeof import('./src/components/header/user/user.vue')['default']
  }
}

export {}
