// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Backtop: typeof import('./src/components/backtop/backtop.vue')['default']
    CountUp: typeof import('./src/components/count-up/count-up.vue')['default']
    Default: typeof import('./src/components/loading/default/default.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    Emoji: typeof import('./src/components/md-edits/emoji/emoji.vue')['default']
    Github: typeof import('./src/components/header/github/github.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    I18n: typeof import('./src/components/I18n/index.vue')['default']
    Icon: typeof import('./src/components/icon/icon.vue')['default']
    Lang: typeof import('./src/components/header/lang/lang.vue')['default']
    Logo: typeof import('./src/components/header/logo/logo.vue')['default']
    Manage: typeof import('./src/components/manage/manage.vue')['default']
    Menus: typeof import('./src/components/menus/menus.vue')['default']
    Read: typeof import('./src/components/md-edits/read/read.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./src/components/header/theme/theme.vue')['default']
    UploadImg: typeof import('./src/components/upload/upload-img.vue')['default']
    User: typeof import('./src/components/header/user/user.vue')['default']
  }
}

export {}
