// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Backtop: typeof import('./src/components/backtop/backtop.vue')['default']
    BlogSearch: typeof import('./src/components/header/blog-search/blog-search.vue')['default']
    CommentInput: typeof import('./src/components/comment-input/comment-input.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Emoji: typeof import('./src/components/emoji/emoji.vue')['default']
    Github: typeof import('./src/components/header/github/github.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    I18n: typeof import('./src/components/I18n/index.vue')['default']
    Lang: typeof import('./src/components/header/lang/lang.vue')['default']
    Logo: typeof import('./src/components/header/logo/logo.vue')['default']
    LogoSvg: typeof import('./src/components/logo/logo-svg.vue')['default']
    Manage: typeof import('./src/components/manage/manage.vue')['default']
    MdEmoji: typeof import('./src/components/md-edits/md-emoji/md-emoji.vue')['default']
    Menus: typeof import('./src/components/menus/menus.vue')['default']
    MonacoEditor: typeof import('./src/components/monaco-editor/monaco-editor.vue')['default']
    Nav: typeof import('./src/components/header/nav/nav.vue')['default']
    Read: typeof import('./src/components/md-edits/read/read.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./src/components/header/theme/theme.vue')['default']
    UploadImg: typeof import('./src/components/upload/upload-img.vue')['default']
    User: typeof import('./src/components/header/user/user.vue')['default']
  }
}

export {}
